---
title: "Publications"
---

## Articles and Working Papers

- Introducing the Ethnic Diversity in Xinjiang Dataset, 2024, *Working Paper*, available at SSRN: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4980682>.

- With Matthias vom Hau: Nation-Building Trends in Latin America: The "Multicultural Turn" in Context (Working Title), *Work in Progress*.

- With Emre Amasyali and Andrei Tarasov: State-Sponsored Cultural Genocide: A Global Perspective (Working Title), *Work in Progress*.


## Presentations and invited talks

-   2025: ETHNICGOODS - ICSOH-CONICET Taller Internacional: "Políticas Públicas en Disputa - Multiculturalismo y Gobernanza de la Educación, la Salud y el Territorio en Argentina y América Latina", Salta, Argentina, work-in-progress presentation of "Nation-Building Trends in Latin America", with Matthias vom Hau.

-   2023: Diplomado de Herramientas para el Liderazgo Político y la Gestión Pública Eficiente: "La Guerra en Ucrania",  Fundactión Feliciano Martinez / Universidad San Ignacio de Layola, panel discussion participation.
